name: Create A Release Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip tag')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Extract information
      run: |
        echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        echo "##[set-output name=message;]$(echo '${{ github.event.head_commit.message }}' | egrep -v '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
      id: extract

    - name: Check the extraction version information
      run: |
        echo ${{ steps.extract.outputs.version }}

    - name: Create Release
      uses: actions/create-release@latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.extract.outputs.version }} 
        release_name: ${{ steps.extract.outputs.version }}
        body: |
            ${{ steps.extract.outputs.message }}
        draft: false
        prerelease: false

    - name: Slack notification success
      uses: Ilshidur/action-slack@2.1.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_CHANNEL: web-experience-alert
        SLACK_AVATAR: repository
      with:
        args: "Website ${{ steps.extract.outputs.version }}\n${{ steps.extract.outputs.message }}"
