name: Sync With Main
on:
  push:
    branches:
      - main
jobs:
  release_www:
    runs-on: ubuntu-latest
    steps:
      - name: Sync release/www with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync release/www with main'
          type: now
          from_branch: main
          target_branch: release/www
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[release/www]`.'
        if: failure()

  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Sync develop with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync develop with main'
          type: now
          from_branch: main
          target_branch: develop
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[develop]`.'
        if: failure()

  hotfix_1:
    runs-on: ubuntu-latest
    steps:
      - name: Sync hotfix/1 with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync hotfix/1 with main'
          type: now
          from_branch: main
          target_branch: hotfix/1
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[hotfix/1]`.'
        if: failure()

  release_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Sync release/blog with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync release/blog with main'
          type: now
          from_branch: main
          target_branch: release/blog
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[release/blog]`.'
        if: failure()

  release_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Sync release/docs with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync release/docs with main'
          type: now
          from_branch: main
          target_branch: release/docs
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[release/docs]`.'
        if: failure()

  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Sync qa with main
        if: always()
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: 'Sync qa with main'
          type: now
          from_branch: main
          target_branch: qa
      - name: Slack notification failure
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_CHANNEL: web-experience-alert
          SLACK_AVATAR: repository
        with:
          args: 'Failed to synchronize branches - `[qa]`.'
        if: failure()